// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgcnbcroxhomijgdeqco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnY25iY3JveGhvbWlqZ2RlcWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTQ2MjcsImV4cCI6MjA3MDk5MDYyN30.iZMIzpbGdE8tWfGn3XTbAid4BQdfWwx7DXheAxF8nWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});